# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Keep GitHub Actions up to date.
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "github-actions"

  # Root package.
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "monthly"
    versioning-strategy: "widen"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "php"

  # Components (exported to their own repositories via subtree).
  - package-ecosystem: "composer"
    directory: "/src/Common"
    schedule:
      interval: "monthly"
    versioning-strategy: "widen"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "php"
      - "common"
  - package-ecosystem: "composer"
    directory: "/src/Http"
    schedule:
      interval: "monthly"
    versioning-strategy: "widen"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "php"
      - "http"
  - package-ecosystem: "composer"
    directory: "/src/Plugin"
    schedule:
      interval: "monthly"
    versioning-strategy: "widen"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "php"
      - "plugin"
